File:
  outputDir: "./test_data/output/" # Str | Path to directory to output results such as term vocabulary, embedding weights, etc
  saveCSV: "True" # Boolean | indicates whether to save output as a CSV
  workorderPath: "./test_data/test.csv" # Str | location to .csv or .xlsx file of maintenance work order records from CMMS
Settings:
  collocationCandidates: 5 # Int | Number of collocation candidates to present
Data:
  CMMSType: "SAP" # Str | Options: "1SAP", "SAP", "JDE"
  outputPrefix: "test" # Str | Prefix for discriminating against output data files
  workorderColNames:
    FUNCTIONAL_LOC: "Work Order Functional Location" # Str | Example: "Work Order Functional Location"
    FUNCTIONAL_LOC_DESC: "Functional Location Description" # Str | Example: "Functional Location Description"
    WO_DESCRIPTION: "Work Order Description" # Str | Example: "Work Order Description"
    CREATION_DATE: "Work Order Created On Timestamp (UTC)" # Str | Example: "Work Order Created On Timestamp (UTC)"
    BASIC_START_DATE: "Work Order Basic Start Date" # Str | Example: "Work Order Basic Start Date"
    BASIC_FINISH_DATE: "Work Order Basic Finish Date" # Str | Example: "Work Order Basic Finish Date"
    ACTUAL_START_DATE: "Work Order Actual Start Timestamp" # Str | Example: "Work Order Actual Start Timestamp"
    ACTUAL_FINISH_DATE: "Work Order Actual Finish Timestamp" # Str | Example: "Work Order Actual Finish Timestamp"
    TOTAL_ACTUAL_HOURS: "Work Order Actual Total Hours" # Str | Example: "Work Order Actual Total Hours"
    TOTAL_ACTUAL_COST: "Work Order Total Actual Costs" # Str | "Work Order Total Actual Costs"
    # Classification is either WO TYPE in SAP or Classification in JDE (preventative, corrective, etc.)
    WO_CLASSIFICATION: "Work Order Type" # Str | "Work Order Type"
    # High level object type (if avaialble) - identicates clearly what type of object e.g. pump, motor, conveyor, etc.
    OBJECT_TYPE: "Functional Location Object Type Description" # Str | "Functional Location Object Type Description"
    ACTIVITY_TYPE: # Str | JDE specific - this has repair, overhaul, rebuild etc, classifications for work orders.
    additionalCols: # List(Str)
      - "Assembly Description"
  filters:
    dateLower: "2011-01-01" # Str | Example: "2011-01-01"
    dateUpper: "" # Str | Example: ""
    # objectType will be via substring matching (leave empty if not required)
    objectType: "pump" # Str | Example: "pump"
    # Drop any rows where NA exists in woDescription or (cost and hours) or actual start datetime
    dropNA: "True" # Str | Example: True
    # Minimum total wo cost (dollars)
    costMin: "2000" # Str | Example: 2000
    # Minimum total wo hours (hrs)
    hourMin: "8" # Str | Example: 8
Calculation:
  # Number of failure/suspension data points required for parameter estimate
  noDataPoints: "5" # Str | Example: 5
